// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: filelister/v1/filelister.proto

package filelisterv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/apipb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dir           string                 `protobuf:"bytes,1,opt,name=dir,proto3" json:"dir,omitempty"`
	HostFsBroker  uint32                 `protobuf:"varint,2,opt,name=host_fs_broker,json=hostFsBroker,proto3" json:"host_fs_broker,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileListRequest) Reset() {
	*x = FileListRequest{}
	mi := &file_filelister_v1_filelister_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileListRequest) ProtoMessage() {}

func (x *FileListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filelister_v1_filelister_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileListRequest.ProtoReflect.Descriptor instead.
func (*FileListRequest) Descriptor() ([]byte, []int) {
	return file_filelister_v1_filelister_proto_rawDescGZIP(), []int{0}
}

func (x *FileListRequest) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

func (x *FileListRequest) GetHostFsBroker() uint32 {
	if x != nil {
		return x.HostFsBroker
	}
	return 0
}

type FileListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         []string               `protobuf:"bytes,1,rep,name=entry,proto3" json:"entry,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileListResponse) Reset() {
	*x = FileListResponse{}
	mi := &file_filelister_v1_filelister_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileListResponse) ProtoMessage() {}

func (x *FileListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filelister_v1_filelister_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileListResponse.ProtoReflect.Descriptor instead.
func (*FileListResponse) Descriptor() ([]byte, []int) {
	return file_filelister_v1_filelister_proto_rawDescGZIP(), []int{1}
}

func (x *FileListResponse) GetEntry() []string {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *FileListResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

var File_filelister_v1_filelister_proto protoreflect.FileDescriptor

const file_filelister_v1_filelister_proto_rawDesc = "" +
	"\n" +
	"\x1efilelister/v1/filelister.proto\x12\rfilelister.v1\x1a\x19google/protobuf/api.proto\"I\n" +
	"\x0fFileListRequest\x12\x10\n" +
	"\x03dir\x18\x01 \x01(\tR\x03dir\x12$\n" +
	"\x0ehost_fs_broker\x18\x02 \x01(\rR\fhostFsBroker\"M\n" +
	"\x10FileListResponse\x12\x14\n" +
	"\x05entry\x18\x01 \x03(\tR\x05entry\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error2U\n" +
	"\n" +
	"FileLister\x12G\n" +
	"\x04List\x12\x1e.filelister.v1.FileListRequest\x1a\x1f.filelister.v1.FileListResponseB\xc2\x01\n" +
	"\x11com.filelister.v1B\x0fFilelisterProtoP\x01ZGgithub.com/bmj2728/PlugsConc/shared/protogen/filelister/v1;filelisterv1\xa2\x02\x03FXX\xaa\x02\rFilelister.V1\xca\x02\rFilelister\\V1\xe2\x02\x19Filelister\\V1\\GPBMetadata\xea\x02\x0eFilelister::V1b\x06proto3"

var (
	file_filelister_v1_filelister_proto_rawDescOnce sync.Once
	file_filelister_v1_filelister_proto_rawDescData []byte
)

func file_filelister_v1_filelister_proto_rawDescGZIP() []byte {
	file_filelister_v1_filelister_proto_rawDescOnce.Do(func() {
		file_filelister_v1_filelister_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_filelister_v1_filelister_proto_rawDesc), len(file_filelister_v1_filelister_proto_rawDesc)))
	})
	return file_filelister_v1_filelister_proto_rawDescData
}

var file_filelister_v1_filelister_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_filelister_v1_filelister_proto_goTypes = []any{
	(*FileListRequest)(nil),  // 0: filelister.v1.FileListRequest
	(*FileListResponse)(nil), // 1: filelister.v1.FileListResponse
}
var file_filelister_v1_filelister_proto_depIdxs = []int32{
	0, // 0: filelister.v1.FileLister.List:input_type -> filelister.v1.FileListRequest
	1, // 1: filelister.v1.FileLister.List:output_type -> filelister.v1.FileListResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_filelister_v1_filelister_proto_init() }
func file_filelister_v1_filelister_proto_init() {
	if File_filelister_v1_filelister_proto != nil {
		return
	}
	file_filelister_v1_filelister_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_filelister_v1_filelister_proto_rawDesc), len(file_filelister_v1_filelister_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_filelister_v1_filelister_proto_goTypes,
		DependencyIndexes: file_filelister_v1_filelister_proto_depIdxs,
		MessageInfos:      file_filelister_v1_filelister_proto_msgTypes,
	}.Build()
	File_filelister_v1_filelister_proto = out.File
	file_filelister_v1_filelister_proto_goTypes = nil
	file_filelister_v1_filelister_proto_depIdxs = nil
}
