// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: filesystem/v1/fs.proto

package filesystemv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFileRequest) Reset() {
	*x = ListFileRequest{}
	mi := &file_filesystem_v1_fs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFileRequest) ProtoMessage() {}

func (x *ListFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_v1_fs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFileRequest.ProtoReflect.Descriptor instead.
func (*ListFileRequest) Descriptor() ([]byte, []int) {
	return file_filesystem_v1_fs_proto_rawDescGZIP(), []int{0}
}

func (x *ListFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ListFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      []string               `protobuf:"bytes,1,rep,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFileResponse) Reset() {
	*x = ListFileResponse{}
	mi := &file_filesystem_v1_fs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFileResponse) ProtoMessage() {}

func (x *ListFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_v1_fs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFileResponse.ProtoReflect.Descriptor instead.
func (*ListFileResponse) Descriptor() ([]byte, []int) {
	return file_filesystem_v1_fs_proto_rawDescGZIP(), []int{1}
}

func (x *ListFileResponse) GetFilename() []string {
	if x != nil {
		return x.Filename
	}
	return nil
}

type IsDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsDirRequest) Reset() {
	*x = IsDirRequest{}
	mi := &file_filesystem_v1_fs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsDirRequest) ProtoMessage() {}

func (x *IsDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_v1_fs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsDirRequest.ProtoReflect.Descriptor instead.
func (*IsDirRequest) Descriptor() ([]byte, []int) {
	return file_filesystem_v1_fs_proto_rawDescGZIP(), []int{2}
}

func (x *IsDirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type IsDirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsDir         bool                   `protobuf:"varint,1,opt,name=isDir,proto3" json:"isDir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsDirResponse) Reset() {
	*x = IsDirResponse{}
	mi := &file_filesystem_v1_fs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsDirResponse) ProtoMessage() {}

func (x *IsDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_v1_fs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsDirResponse.ProtoReflect.Descriptor instead.
func (*IsDirResponse) Descriptor() ([]byte, []int) {
	return file_filesystem_v1_fs_proto_rawDescGZIP(), []int{3}
}

func (x *IsDirResponse) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

var File_filesystem_v1_fs_proto protoreflect.FileDescriptor

const file_filesystem_v1_fs_proto_rawDesc = "" +
	"\n" +
	"\x16filesystem/v1/fs.proto\x12\rfilesystem.v1\"%\n" +
	"\x0fListFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\".\n" +
	"\x10ListFileResponse\x12\x1a\n" +
	"\bfilename\x18\x01 \x03(\tR\bfilename\"\"\n" +
	"\fIsDirRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"%\n" +
	"\rIsDirResponse\x12\x14\n" +
	"\x05isDir\x18\x01 \x01(\bR\x05isDir2\x9e\x01\n" +
	"\n" +
	"FileSystem\x12L\n" +
	"\tListFiles\x12\x1e.filesystem.v1.ListFileRequest\x1a\x1f.filesystem.v1.ListFileResponse\x12B\n" +
	"\x05IsDir\x12\x1b.filesystem.v1.IsDirRequest\x1a\x1c.filesystem.v1.IsDirResponseB\xba\x01\n" +
	"\x11com.filesystem.v1B\aFsProtoP\x01ZGgithub.com/bmj2728/PlugsConc/shared/protogen/filesystem/v1;filesystemv1\xa2\x02\x03FXX\xaa\x02\rFilesystem.V1\xca\x02\rFilesystem\\V1\xe2\x02\x19Filesystem\\V1\\GPBMetadata\xea\x02\x0eFilesystem::V1b\x06proto3"

var (
	file_filesystem_v1_fs_proto_rawDescOnce sync.Once
	file_filesystem_v1_fs_proto_rawDescData []byte
)

func file_filesystem_v1_fs_proto_rawDescGZIP() []byte {
	file_filesystem_v1_fs_proto_rawDescOnce.Do(func() {
		file_filesystem_v1_fs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_filesystem_v1_fs_proto_rawDesc), len(file_filesystem_v1_fs_proto_rawDesc)))
	})
	return file_filesystem_v1_fs_proto_rawDescData
}

var file_filesystem_v1_fs_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_filesystem_v1_fs_proto_goTypes = []any{
	(*ListFileRequest)(nil),  // 0: filesystem.v1.ListFileRequest
	(*ListFileResponse)(nil), // 1: filesystem.v1.ListFileResponse
	(*IsDirRequest)(nil),     // 2: filesystem.v1.IsDirRequest
	(*IsDirResponse)(nil),    // 3: filesystem.v1.IsDirResponse
}
var file_filesystem_v1_fs_proto_depIdxs = []int32{
	0, // 0: filesystem.v1.FileSystem.ListFiles:input_type -> filesystem.v1.ListFileRequest
	2, // 1: filesystem.v1.FileSystem.IsDir:input_type -> filesystem.v1.IsDirRequest
	1, // 2: filesystem.v1.FileSystem.ListFiles:output_type -> filesystem.v1.ListFileResponse
	3, // 3: filesystem.v1.FileSystem.IsDir:output_type -> filesystem.v1.IsDirResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_filesystem_v1_fs_proto_init() }
func file_filesystem_v1_fs_proto_init() {
	if File_filesystem_v1_fs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_filesystem_v1_fs_proto_rawDesc), len(file_filesystem_v1_fs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_filesystem_v1_fs_proto_goTypes,
		DependencyIndexes: file_filesystem_v1_fs_proto_depIdxs,
		MessageInfos:      file_filesystem_v1_fs_proto_msgTypes,
	}.Build()
	File_filesystem_v1_fs_proto = out.File
	file_filesystem_v1_fs_proto_goTypes = nil
	file_filesystem_v1_fs_proto_depIdxs = nil
}
