// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: animal/v1/animal.proto

package animalv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Animal_Speak_FullMethodName = "/animal.v1.Animal/Speak"
)

// AnimalClient is the client API for Animal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnimalClient interface {
	Speak(ctx context.Context, in *SpeakRequest, opts ...grpc.CallOption) (*SpeakResponse, error)
}

type animalClient struct {
	cc grpc.ClientConnInterface
}

func NewAnimalClient(cc grpc.ClientConnInterface) AnimalClient {
	return &animalClient{cc}
}

func (c *animalClient) Speak(ctx context.Context, in *SpeakRequest, opts ...grpc.CallOption) (*SpeakResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpeakResponse)
	err := c.cc.Invoke(ctx, Animal_Speak_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnimalServer is the server API for Animal service.
// All implementations must embed UnimplementedAnimalServer
// for forward compatibility.
type AnimalServer interface {
	Speak(context.Context, *SpeakRequest) (*SpeakResponse, error)
	mustEmbedUnimplementedAnimalServer()
}

// UnimplementedAnimalServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnimalServer struct{}

func (UnimplementedAnimalServer) Speak(context.Context, *SpeakRequest) (*SpeakResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Speak not implemented")
}
func (UnimplementedAnimalServer) mustEmbedUnimplementedAnimalServer() {}
func (UnimplementedAnimalServer) testEmbeddedByValue()                {}

// UnsafeAnimalServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnimalServer will
// result in compilation errors.
type UnsafeAnimalServer interface {
	mustEmbedUnimplementedAnimalServer()
}

func RegisterAnimalServer(s grpc.ServiceRegistrar, srv AnimalServer) {
	// If the following call pancis, it indicates UnimplementedAnimalServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Animal_ServiceDesc, srv)
}

func _Animal_Speak_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpeakRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnimalServer).Speak(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Animal_Speak_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnimalServer).Speak(ctx, req.(*SpeakRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Animal_ServiceDesc is the grpc.ServiceDesc for Animal service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Animal_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "animal.v1.Animal",
	HandlerType: (*AnimalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Speak",
			Handler:    _Animal_Speak_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "animal/v1/animal.proto",
}
